"""Deterministic builders for the narrow DICOM subset used by the tests.

The produced files are hand-serialized (no third-party DICOM dependency) so
that corruption can be injected at exact byte/element boundaries.
"""

from __future__ import annotations

import struct

TS_JPEG_BASELINE = "1.2.840.10008.1.2.4.50"
TS_JPEG_LS_LOSSLESS = "1.2.840.10008.1.2.4.70"
TS_EXPLICIT_VR_LITTLE_ENDIAN = "1.2.840.10008.1.2.1"

_EXTENDED_VRS = frozenset({"OB", "OD", "OF", "OL", "OV", "OW", "SQ", "UC", "UN", "UR", "UT"})

ITEM = 0xFFFEE000
ITEM_DELIM = 0xFFFEE00D
SEQ_DELIM = 0xFFFEE0DD
UNDEFINED = 0xFFFFFFFF


def item_header(tag32: int, length: int) -> bytes:
    """Serialize an item/delimiter tag as two little-endian 16-bit halves."""
    return struct.pack("<HHI", tag32 >> 16, tag32 & 0xFFFF, length)


# --------------------------------------------------------------------------- #
# Data elements (Explicit VR Little Endian)
# --------------------------------------------------------------------------- #

def evr(group: int, element: int, vr: str, value: bytes) -> bytes:
    tag = struct.pack("<HH", group, element)
    vr_b = vr.encode("ascii")
    if vr in _EXTENDED_VRS:
        return tag + vr_b + b"\x00\x00" + struct.pack("<I", len(value)) + value
    return tag + vr_b + struct.pack("<H", len(value)) + value


def ui_value(text: str) -> bytes:
    raw = text.encode("ascii")
    return raw + (b"\x00" if len(raw) % 2 else b"")


def is_value(number: int) -> bytes:
    raw = str(number).encode("ascii")
    return raw + (b" " if len(raw) % 2 else b"")


# --------------------------------------------------------------------------- #
# Minimal structurally-valid Baseline JPEG (SOF0) stream
# --------------------------------------------------------------------------- #

def jpeg_stream(seed: int = 0, *, sof_marker: int = 0xC0, with_restart: bool = False,
                soi: bool = True, eoi: bool = True, pad_to_even: bool = True,
                force_odd: bool = False) -> bytes:
    """Return a tiny marker-valid Baseline JPEG-like stream.

    Pixel content is irrelevant: the service validates marker structure, it
    does not decode entropy data. The stream includes a byte-stuffed 0xFF00
    pair and, optionally, an RSTn marker inside the entropy scan.
    """
    parts: list[bytes] = []
    parts.append(b"\xff\xd8" if soi else b"\xff\x00")

    # APP0 JFIF, length 16
    parts.append(b"\xff\xe0" + struct.pack(">H", 16) + b"JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00")
    # DQT: one 8-bit table
    dqt = bytes([0x00]) + bytes(((i * 7 + seed) & 0xFF for i in range(64)))
    parts.append(b"\xff\xdb" + struct.pack(">H", 2 + 1 + 64) + dqt)
    # SOFn: 8-bit, 1x1, 1 component
    sof = bytes([8, 0, 1, 0, 1, 1, 0x11, 0])
    parts.append(b"\xff" + bytes([sof_marker]) + struct.pack(">H", 2 + len(sof)) + sof)
    # DHT: one DC table, payload content not semantically checked
    dht = bytes([0x00]) + bytes(range(17))
    parts.append(b"\xff\xc4" + struct.pack(">H", 2 + len(dht)) + dht)
    # SOS: 1 component (id 1, DC/AC 0/0), Ss=0 Se=63 Ah/Al=0
    sos = bytes([1, 1, 0x00, 0, 63, 0x00])
    parts.append(b"\xff\xda" + struct.pack(">H", 2 + len(sos)) + sos)

    # Entropy payloads may never contain a raw 0xFF except as FF00 stuffing
    # or a marker, so keep generated bytes below 0xFF.
    entropy = bytes([(seed * 37 + 11) & 0x7F, 0xAA, 0xFF, 0x00, 0x3C])
    if with_restart:
        entropy += b"\x11\xff\xd0\x22"
    eoi = b"\xff\xd9" if eoi else b"\xff\x00"
    # Encapsulated item values must be even length; pad the entropy payload
    # (not the EOI marker) until the whole stream is even.
    header = b"".join(parts)
    if pad_to_even:
        while (len(header) + len(entropy) + len(eoi)) % 2:
            entropy += b"\x7e"
    elif force_odd:
        while (len(header) + len(entropy) + len(eoi)) % 2 == 0:
            entropy += b"\x7e"
    parts.append(entropy)
    parts.append(eoi)
    return b"".join(parts)


# --------------------------------------------------------------------------- #
# Encapsulated pixel data
# --------------------------------------------------------------------------- #

def encapsulated_pixel_data(
    frame_fragments: list[list[bytes]],
    *,
    bot_entries: list[int] | None = None,
    bot_value: bytes | None = None,
    bot_item_length: int | None = None,
    undefined_fragment_items: bool = False,
    sequence_delim_length: int = 0,
) -> bytes:
    """Build the value-stream of an undefined-length OB Pixel Data element."""
    items = bytearray()
    natural_offsets: list[int] = []
    normalized = [[f] if isinstance(f, (bytes, bytearray)) else list(f) for f in frame_fragments]
    for fragments in normalized:
        for j, payload in enumerate(fragments):
            if j == 0:
                natural_offsets.append(len(items))
            # A conformant encoder pads the LAST fragment of a frame to an even
            # item length with a single NUL after the encoded stream. Test
            # cuts are chosen so non-last fragments are already even.
            if j == len(fragments) - 1 and len(payload) % 2:
                payload = payload + b"\x00"
            if undefined_fragment_items:
                items += item_header(ITEM, UNDEFINED) + payload
                items += item_header(ITEM_DELIM, 0)
            else:
                items += item_header(ITEM, len(payload)) + payload

    if bot_value is None:
        entries = natural_offsets if bot_entries is None else bot_entries
        bot_value = struct.pack(f"<{len(entries)}I", *entries) if entries else b""
    length = bot_item_length if bot_item_length is not None else len(bot_value)
    bot = item_header(ITEM, length) + bot_value

    return bytes(bot) + bytes(items) + item_header(SEQ_DELIM, sequence_delim_length)


# --------------------------------------------------------------------------- #
# Full Part 10 file
# --------------------------------------------------------------------------- #

def build_dicom(
    frames: list[bytes | list[bytes]],
    *,
    transfer_syntax: str = TS_JPEG_BASELINE,
    declared_frames: int | None = None,
    number_of_frames_raw: bytes | None = None,
    include_number_of_frames: bool = True,
    bot_entries: list[int] | None = None,
    bot_value: bytes | None = None,
    bot_item_length: int | None = None,
    undefined_fragment_items: bool = False,
    sequence_delim_length: int = 0,
    pixel_data_length: int | None = UNDEFINED,
    pixel_data_stream: bytes | None = None,
    trailing: bytes = b"",
    meta_length_delta: int = 0,
    preamble: bytes | None = None,
    magic: bytes = b"DICM",
    undefined_prefix_element: bool = False,
    extra_before_pixel: bytes = b"",
    extra_after_number: bytes = b"",
) -> bytes:
    normalized: list[list[bytes]] = [[f] if isinstance(f, (bytes, bytearray)) else list(f) for f in frames]
    nframes = declared_frames if declared_frames is not None else len(normalized)

    # ---- file meta information ----
    meta_body = evr(0x0002, 0x0010, "UI", ui_value(transfer_syntax))
    meta_body += evr(0x0002, 0x0012, "UI", ui_value("1.2.3.4.5"))
    meta = evr(0x0002, 0x0000, "UL", struct.pack("<I", len(meta_body) + meta_length_delta))
    meta += meta_body

    # ---- main dataset ----
    dataset = b""
    dataset += evr(0x0008, 0x0060, "CS", b"SM")  # Modality
    dataset += evr(0x0028, 0x0002, "US", struct.pack("<H", 3))  # SamplesPerPixel
    if include_number_of_frames:
        if number_of_frames_raw is not None:
            dataset += evr(0x0028, 0x0008, "IS", number_of_frames_raw)
        else:
            dataset += evr(0x0028, 0x0008, "IS", is_value(nframes))
    dataset += evr(0x0028, 0x0010, "US", struct.pack("<H", 1))  # Rows
    dataset += evr(0x0028, 0x0011, "US", struct.pack("<H", 1))  # Columns
    dataset += extra_after_number
    dataset += extra_before_pixel

    if undefined_prefix_element:
        # (0028,1101) RedPaletteColorLookupTableData SQ with undefined length.
        dataset += struct.pack("<HHBBHI", 0x0028, 0x1101, ord("S"), ord("Q"), 0, UNDEFINED)

    if pixel_data_stream is None:
        pixel_data_stream = encapsulated_pixel_data(
            normalized,
            bot_entries=bot_entries,
            bot_value=bot_value,
            bot_item_length=bot_item_length,
            undefined_fragment_items=undefined_fragment_items,
            sequence_delim_length=sequence_delim_length,
        )
    dataset += struct.pack("<HH", 0x7FE0, 0x0010) + b"OB\x00\x00" + struct.pack("<I", pixel_data_length)
    if pixel_data_length == UNDEFINED:
        dataset += pixel_data_stream

    pre = preamble if preamble is not None else b"\x00" * 128
    return pre + magic + meta + dataset + trailing


def split_frame(payload: bytes, cuts: tuple[int, ...]) -> list[bytes]:
    """Split one frame payload into multiple fragments at the given offsets."""
    bounds = (0,) + cuts + (len(payload),)
    return [payload[a:b] for a, b in zip(bounds, bounds[1:])]
